//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 04:33:39 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.998.431", 
xmlns = {
@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:iso:std:iso:20022:tech:xsd:camt.998.431", prefix = "bimo")},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.belejanor.switcher.bimo.pacs.camt_998_431;
