//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 02:28:55 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_211;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AcctEnroll complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctEnroll">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartyNm" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max140Text"/>
 *         &lt;element name="PartyId" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text"/>
 *         &lt;element name="PartyDocType" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}DocType"/>
 *         &lt;element name="PINBimo" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}PINType"/>
 *         &lt;element name="PartyPerfil" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}ProfileType"/>
 *         &lt;element name="PartyDocCtry" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="PartyPrdType" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text"/>
 *         &lt;element name="PartyPhone" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}PhoneType"/>
 *         &lt;element name="PartyEmail" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}EmailType" minOccurs="0"/>
 *         &lt;element name="PartyBrdDt" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}ISODate"/>
 *         &lt;element name="CodigoDactilar" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="AcctInfo" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}AccountId"/>
 *         &lt;element name="Gender" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="PartyIssueDate" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}ISODate" minOccurs="0"/>
 *         &lt;element name="MaritalSts" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="Occupation" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="Instruction" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}Max35Text" minOccurs="0"/>
 *         &lt;element name="SttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.211}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctEnroll", propOrder = {
    "partyNm",
    "partyId",
    "partyDocType",
    "pinBimo",
    "partyPerfil",
    "partyDocCtry",
    "partyPrdType",
    "partyPhone",
    "partyEmail",
    "partyBrdDt",
    "codigoDactilar",
    "acctInfo",
    "gender",
    "partyIssueDate",
    "maritalSts",
    "occupation",
    "instruction",
    "sttlmDt"
})
public class AcctEnroll implements Serializable{

    @XmlElement(name = "PartyNm", required = true)
    protected String partyNm;
    @XmlElement(name = "PartyId", required = true)
    protected String partyId;
    @XmlElement(name = "PartyDocType", required = true)
    protected String partyDocType;
    @XmlElement(name = "PINBimo", required = true)
    protected String pinBimo;
    @XmlElement(name = "PartyPerfil", required = true)
    protected String partyPerfil;
    @XmlElement(name = "PartyDocCtry")
    protected String partyDocCtry;
    @XmlElement(name = "PartyPrdType", required = true)
    protected String partyPrdType;
    @XmlElement(name = "PartyPhone", required = true)
    protected String partyPhone;
    @XmlElement(name = "PartyEmail")
    protected String partyEmail;
    @XmlElement(name = "PartyBrdDt", required = true)
    protected XMLGregorianCalendar partyBrdDt;
    @XmlElement(name = "CodigoDactilar")
    protected String codigoDactilar;
    @XmlElement(name = "AcctInfo", required = true)
    protected String acctInfo;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "PartyIssueDate")
    protected XMLGregorianCalendar partyIssueDate;
    @XmlElement(name = "MaritalSts")
    protected String maritalSts;
    @XmlElement(name = "Occupation")
    protected String occupation;
    @XmlElement(name = "Instruction")
    protected String instruction;
    @XmlElement(name = "SttlmDt", required = true)
    protected XMLGregorianCalendar sttlmDt;

    /**
     * Gets the value of the partyNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNm() {
        return partyNm;
    }

    /**
     * Sets the value of the partyNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNm(String value) {
        this.partyNm = value;
    }

    /**
     * Gets the value of the partyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * Sets the value of the partyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyId(String value) {
        this.partyId = value;
    }

    /**
     * Gets the value of the partyDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyDocType() {
        return partyDocType;
    }

    /**
     * Sets the value of the partyDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyDocType(String value) {
        this.partyDocType = value;
    }

    /**
     * Gets the value of the pinBimo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINBimo() {
        return pinBimo;
    }

    /**
     * Sets the value of the pinBimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINBimo(String value) {
        this.pinBimo = value;
    }

    /**
     * Gets the value of the partyPerfil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPerfil() {
        return partyPerfil;
    }

    /**
     * Sets the value of the partyPerfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPerfil(String value) {
        this.partyPerfil = value;
    }

    /**
     * Gets the value of the partyDocCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyDocCtry() {
        return partyDocCtry;
    }

    /**
     * Sets the value of the partyDocCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyDocCtry(String value) {
        this.partyDocCtry = value;
    }

    /**
     * Gets the value of the partyPrdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPrdType() {
        return partyPrdType;
    }

    /**
     * Sets the value of the partyPrdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPrdType(String value) {
        this.partyPrdType = value;
    }

    /**
     * Gets the value of the partyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPhone() {
        return partyPhone;
    }

    /**
     * Sets the value of the partyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPhone(String value) {
        this.partyPhone = value;
    }

    /**
     * Gets the value of the partyEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyEmail() {
        return partyEmail;
    }

    /**
     * Sets the value of the partyEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyEmail(String value) {
        this.partyEmail = value;
    }

    /**
     * Gets the value of the partyBrdDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartyBrdDt() {
        return partyBrdDt;
    }

    /**
     * Sets the value of the partyBrdDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartyBrdDt(XMLGregorianCalendar value) {
        this.partyBrdDt = value;
    }

    /**
     * Gets the value of the codigoDactilar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDactilar() {
        return codigoDactilar;
    }

    /**
     * Sets the value of the codigoDactilar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDactilar(String value) {
        this.codigoDactilar = value;
    }

    /**
     * Gets the value of the acctInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctInfo() {
        return acctInfo;
    }

    /**
     * Sets the value of the acctInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctInfo(String value) {
        this.acctInfo = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the partyIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartyIssueDate() {
        return partyIssueDate;
    }

    /**
     * Sets the value of the partyIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartyIssueDate(XMLGregorianCalendar value) {
        this.partyIssueDate = value;
    }

    /**
     * Gets the value of the maritalSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalSts() {
        return maritalSts;
    }

    /**
     * Sets the value of the maritalSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalSts(String value) {
        this.maritalSts = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the instruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * Sets the value of the instruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstruction(String value) {
        this.instruction = value;
    }

    /**
     * Gets the value of the sttlmDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSttlmDt() {
        return sttlmDt;
    }

    /**
     * Sets the value of the sttlmDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSttlmDt(XMLGregorianCalendar value) {
        this.sttlmDt = value;
    }

}
