//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 02:28:55 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_211;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fitbank.middleware.bimo.pacs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@SuppressWarnings("serial")
@XmlRegistry
public class ObjectFactory implements Serializable{

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.998.211", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fitbank.middleware.bimo.pacs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation }
     * 
     */
    public OriginalGroupInformation createOriginalGroupInformation() {
        return new OriginalGroupInformation();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link CashAccount24 }
     * 
     */
    public CashAccount24 createCashAccount24() {
        return new CashAccount24();
    }

    /**
     * Create an instance of {@link MjeData }
     * 
     */
    public MjeData createMjeData() {
        return new MjeData();
    }

    /**
     * Create an instance of {@link CategoryPurpose }
     * 
     */
    public CategoryPurpose createCategoryPurpose() {
        return new CategoryPurpose();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation }
     * 
     */
    public PaymentTypeInformation createPaymentTypeInformation() {
        return new PaymentTypeInformation();
    }

    /**
     * Create an instance of {@link ZGenericFinancialIdentification }
     * 
     */
    public ZGenericFinancialIdentification createZGenericFinancialIdentification() {
        return new ZGenericFinancialIdentification();
    }

    /**
     * Create an instance of {@link ChargesInformation }
     * 
     */
    public ChargesInformation createChargesInformation() {
        return new ChargesInformation();
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

    /**
     * Create an instance of {@link TransactionInformationAndStatus }
     * 
     */
    public TransactionInformationAndStatus createTransactionInformationAndStatus() {
        return new TransactionInformationAndStatus();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification }
     * 
     */
    public FinancialInstitutionIdentification createFinancialInstitutionIdentification() {
        return new FinancialInstitutionIdentification();
    }

    /**
     * Create an instance of {@link PrivateIdentification }
     * 
     */
    public PrivateIdentification createPrivateIdentification() {
        return new PrivateIdentification();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link ZBranchAndFinancialInstitutionIdentification }
     * 
     */
    public ZBranchAndFinancialInstitutionIdentification createZBranchAndFinancialInstitutionIdentification() {
        return new ZBranchAndFinancialInstitutionIdentification();
    }

    /**
     * Create an instance of {@link HeaderData }
     * 
     */
    public HeaderData createHeaderData() {
        return new HeaderData();
    }

    /**
     * Create an instance of {@link BranchData2 }
     * 
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link SignatureData }
     * 
     */
    public SignatureData createSignatureData() {
        return new SignatureData();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification }
     * 
     */
    public ClearingSystemMemberIdentification createClearingSystemMemberIdentification() {
        return new ClearingSystemMemberIdentification();
    }

    /**
     * Create an instance of {@link ServiceData }
     * 
     */
    public ServiceData createServiceData() {
        return new ServiceData();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link Debtor }
     * 
     */
    public Debtor createDebtor() {
        return new Debtor();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification }
     * 
     */
    public ClearingSystemIdentification createClearingSystemIdentification() {
        return new ClearingSystemIdentification();
    }

    /**
     * Create an instance of {@link AcctEnroll }
     * 
     */
    public AcctEnroll createAcctEnroll() {
        return new AcctEnroll();
    }

    /**
     * Create an instance of {@link ProprietaryMessageV02 }
     * 
     */
    public ProprietaryMessageV02 createProprietaryMessageV02() {
        return new ProprietaryMessageV02();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link GroupHeader }
     * 
     */
    public GroupHeader createGroupHeader() {
        return new GroupHeader();
    }

    /**
     * Create an instance of {@link PaymentIdentification }
     * 
     */
    public PaymentIdentification createPaymentIdentification() {
        return new PaymentIdentification();
    }

    /**
     * Create an instance of {@link OtherAUX }
     * 
     */
    public OtherAUX createOtherAUX() {
        return new OtherAUX();
    }

    /**
     * Create an instance of {@link OrigIdData }
     * 
     */
    public OrigIdData createOrigIdData() {
        return new OrigIdData();
    }

    /**
     * Create an instance of {@link SchemeName }
     * 
     */
    public SchemeName createSchemeName() {
        return new SchemeName();
    }

    /**
     * Create an instance of {@link SettlementInstruction4 }
     * 
     */
    public SettlementInstruction4 createSettlementInstruction4() {
        return new SettlementInstruction4();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link StatusReasonInformation }
     * 
     */
    public StatusReasonInformation createStatusReasonInformation() {
        return new StatusReasonInformation();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice }
     * 
     */
    public ClearingSystemIdentification3Choice createClearingSystemIdentification3Choice() {
        return new ClearingSystemIdentification3Choice();
    }

    /**
     * Create an instance of {@link ZFinancialInstitutionIdentification }
     * 
     */
    public ZFinancialInstitutionIdentification createZFinancialInstitutionIdentification() {
        return new ZFinancialInstitutionIdentification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.998.211", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
