//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 02:59:57 PM COT 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.007.001.07.051", 
xmlns = {
@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:iso:std:iso:20022:tech:xsd:pacs.007.001.07.051", prefix = "bimo")},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.belejanor.switcher.bimo.pacs.pacs_007_051;
