//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 02:59:21 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_372;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ListOfPayments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListOfPayments">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}ISODate"/>
 *         &lt;element name="PhoneOrig" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}PhoneType"/>
 *         &lt;element name="NameOrig" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}Max35Text" minOccurs="0"/>
 *         &lt;element name="PhoneDst" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}PhoneType"/>
 *         &lt;element name="NameDst" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}Max35Text" minOccurs="0"/>
 *         &lt;element name="Amount" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}ActiveOrHistoricCurrencyAndAmount"/>
 *         &lt;element name="Reference" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}Max140Text"/>
 *         &lt;element name="AccountDst" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}AccountId"/>
 *         &lt;element name="EndToEnd" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.372}Max35Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfPayments", propOrder = {
    "date",
    "phoneOrig",
    "nameOrig",
    "phoneDst",
    "nameDst",
    "amount",
    "reference",
    "accountDst",
    "endToEnd"
})
public class ListOfPayments implements Serializable{

    @XmlElement(name = "Date", required = true)
    protected XMLGregorianCalendar date;
    @XmlElement(name = "PhoneOrig", required = true)
    protected String phoneOrig;
    @XmlElement(name = "NameOrig")
    protected String nameOrig;
    @XmlElement(name = "PhoneDst", required = true)
    protected String phoneDst;
    @XmlElement(name = "NameDst")
    protected String nameDst;
    @XmlElement(name = "Amount", required = true)
    protected ActiveOrHistoricCurrencyAndAmount amount;
    @XmlElement(name = "Reference", required = true)
    protected String reference;
    @XmlElement(name = "AccountDst", required = true)
    protected String accountDst;
    @XmlElement(name = "EndToEnd", required = true)
    protected String endToEnd;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the phoneOrig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneOrig() {
        return phoneOrig;
    }

    /**
     * Sets the value of the phoneOrig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneOrig(String value) {
        this.phoneOrig = value;
    }

    /**
     * Gets the value of the nameOrig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOrig() {
        return nameOrig;
    }

    /**
     * Sets the value of the nameOrig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOrig(String value) {
        this.nameOrig = value;
    }

    /**
     * Gets the value of the phoneDst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneDst() {
        return phoneDst;
    }

    /**
     * Sets the value of the phoneDst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneDst(String value) {
        this.phoneDst = value;
    }

    /**
     * Gets the value of the nameDst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDst() {
        return nameDst;
    }

    /**
     * Sets the value of the nameDst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDst(String value) {
        this.nameDst = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveOrHistoricCurrencyAndAmount }
     *     
     */
    public ActiveOrHistoricCurrencyAndAmount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveOrHistoricCurrencyAndAmount }
     *     
     */
    public void setAmount(ActiveOrHistoricCurrencyAndAmount value) {
        this.amount = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the accountDst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDst() {
        return accountDst;
    }

    /**
     * Sets the value of the accountDst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDst(String value) {
        this.accountDst = value;
    }

    /**
     * Gets the value of the endToEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndToEnd() {
        return endToEnd;
    }

    /**
     * Sets the value of the endToEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndToEnd(String value) {
        this.endToEnd = value;
    }

}
