//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.26 at 05:17:52 PM COT 
//


package com.belejanor.switcher.bimo.pacs.pacs_008_071;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ContentsV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentsV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustRef" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}Max35Text" minOccurs="0"/>
 *         &lt;element name="ChanRef" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}Max35Text" minOccurs="0"/>
 *         &lt;element name="AgtRef" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}Max35Text" minOccurs="0"/>
 *         &lt;element name="OpeDesc" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}Max140Text" minOccurs="0"/>
 *         &lt;element name="PhOptor" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}Max35Text" minOccurs="0"/>
 *         &lt;element name="DbtCred" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}DebitCredit"/>
 *         &lt;element name="SttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06.071}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentsV01", propOrder = {
    "custRef",
    "chanRef",
    "agtRef",
    "opeDesc",
    "phOptor",
    "dbtCred",
    "sttlmDt"
})
public class ContentsV01 implements Serializable{

    @XmlElement(name = "CustRef")
    protected String custRef;
    @XmlElement(name = "ChanRef")
    protected String chanRef;
    @XmlElement(name = "AgtRef")
    protected String agtRef;
    @XmlElement(name = "OpeDesc")
    protected String opeDesc;
    @XmlElement(name = "PhOptor")
    protected String phOptor;
    @XmlElement(name = "DbtCred", required = true)
    protected DebitCredit dbtCred;
    @XmlElement(name = "SttlmDt", required = true)
    protected XMLGregorianCalendar sttlmDt;

    /**
     * Gets the value of the custRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustRef() {
        return custRef;
    }

    /**
     * Sets the value of the custRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustRef(String value) {
        this.custRef = value;
    }

    /**
     * Gets the value of the chanRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChanRef() {
        return chanRef;
    }

    /**
     * Sets the value of the chanRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChanRef(String value) {
        this.chanRef = value;
    }

    /**
     * Gets the value of the agtRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgtRef() {
        return agtRef;
    }

    /**
     * Sets the value of the agtRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgtRef(String value) {
        this.agtRef = value;
    }

    /**
     * Gets the value of the opeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeDesc() {
        return opeDesc;
    }

    /**
     * Sets the value of the opeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeDesc(String value) {
        this.opeDesc = value;
    }

    /**
     * Gets the value of the phOptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhOptor() {
        return phOptor;
    }

    /**
     * Sets the value of the phOptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhOptor(String value) {
        this.phOptor = value;
    }

    /**
     * Gets the value of the dbtCred property.
     * 
     * @return
     *     possible object is
     *     {@link DebitCredit }
     *     
     */
    public DebitCredit getDbtCred() {
        return dbtCred;
    }

    /**
     * Sets the value of the dbtCred property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitCredit }
     *     
     */
    public void setDbtCred(DebitCredit value) {
        this.dbtCred = value;
    }

    /**
     * Gets the value of the sttlmDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSttlmDt() {
        return sttlmDt;
    }

    /**
     * Sets the value of the sttlmDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSttlmDt(XMLGregorianCalendar value) {
        this.sttlmDt = value;
    }

}
