//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 02:22:51 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_321;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustRef" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.321}Max35Text"/>
 *         &lt;element name="SecretKey" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.321}Max35Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contents", propOrder = {
    "custRef",
    "secretKey"
})
public class Contents implements Serializable{

    @XmlElement(name = "CustRef", required = true)
    protected String custRef;
    @XmlElement(name = "SecretKey")
    protected String secretKey;

    /**
     * Gets the value of the custRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustRef() {
        return custRef;
    }

    /**
     * Sets the value of the custRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustRef(String value) {
        this.custRef = value;
    }

    /**
     * Gets the value of the secretKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * Sets the value of the secretKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecretKey(String value) {
        this.secretKey = value;
    }

}
