//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 04:07:32 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.04", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

/*@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.04",
	    xmlns = { 
	        @javax.xml.bind.annotation.XmlNs(
	            prefix = "urn", 
	            namespaceURI="http://www.bce.fin.ec/wsdl/srr/VentanillaCompartidaSRRWS")
	    }
	    
	)*/

package urn.iso.std.iso20022.tech.xsd.pacs_008_001_04;
