//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 03:55:19 PM COT 
//

/*@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)*/

/*@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05",
	    xmlns = { 
	        @javax.xml.bind.annotation.XmlNs(
	            prefix = "m", 
	            namespaceURI="http://www.bce.fin.ec/wsdl/srr/VentanillaCompartidaSRRWS")//,
	        //@javax.xml.bind.annotation.XmlNs(
		    //        prefix = "urn", 
		    //        namespaceURI="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05"),
	    }
	    
	    
	)*/

@XmlSchema(
    xmlns = { 
        // @XmlNs(prefix = "m", namespaceURI = "http://www.bce.fin.ec/wsdl/srr/VentanillaCompartidaSRRWS")
        //,@XmlNs(prefix = "m", namespaceURI = "http://www.bce.fin.ec/wsdl/srr/TransferenciaElectronicaSRRWS")
        //,@XmlNs(prefix = "m", namespaceURI = "http://www.bce.fin.ec/wsdl/snp/ReversoTecnicoSNPWS")
         @XmlNs(prefix = "m", namespaceURI = "http://www.bce.fin.ec/snp/spi/SolicitudPagoInterbancarioSNPWS")
        ,@XmlNs(prefix = "urn1", namespaceURI = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.04")
        ,@XmlNs(prefix = "urn", namespaceURI = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05")
        ,@XmlNs(prefix = "ns0", namespaceURI = "http://www.bce.fin.ec/wsdl/srr/VentanillaCompartidaSRRWS")
        
    }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)



package urn.iso.std.iso20022.tech.xsd.pacs_002_001_05;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
