//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.07 at 12:38:20 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_311;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BlkUser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlkUser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartyPhone" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}PhoneType"/>
 *         &lt;element name="Action" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}ActionBlk"/>
 *         &lt;element name="PartyNm" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}Max140Text" minOccurs="0"/>
 *         &lt;element name="PartyId" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}Max35Text" minOccurs="0"/>
 *         &lt;element name="PartyDocType" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}DocType" minOccurs="0"/>
 *         &lt;element name="SttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.311}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlkUser", propOrder = {
    "partyPhone",
    "action",
    "partyNm",
    "partyId",
    "partyDocType",
    "sttlmDt"
})
public class BlkUser implements Serializable{

    @XmlElement(name = "PartyPhone", required = true)
    protected String partyPhone;
    @XmlElement(name = "Action", required = true)
    protected ActionBlk action;
    @XmlElement(name = "PartyNm")
    protected String partyNm;
    @XmlElement(name = "PartyId")
    protected String partyId;
    @XmlElement(name = "PartyDocType")
    protected String partyDocType;
    @XmlElement(name = "SttlmDt", required = true)
    protected XMLGregorianCalendar sttlmDt;

    /**
     * Gets the value of the partyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPhone() {
        return partyPhone;
    }

    /**
     * Sets the value of the partyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPhone(String value) {
        this.partyPhone = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionBlk }
     *     
     */
    public ActionBlk getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionBlk }
     *     
     */
    public void setAction(ActionBlk value) {
        this.action = value;
    }

    /**
     * Gets the value of the partyNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNm() {
        return partyNm;
    }

    /**
     * Sets the value of the partyNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNm(String value) {
        this.partyNm = value;
    }

    /**
     * Gets the value of the partyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * Sets the value of the partyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyId(String value) {
        this.partyId = value;
    }

    /**
     * Gets the value of the partyDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyDocType() {
        return partyDocType;
    }

    /**
     * Sets the value of the partyDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyDocType(String value) {
        this.partyDocType = value;
    }

    /**
     * Gets the value of the sttlmDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSttlmDt() {
        return sttlmDt;
    }

    /**
     * Sets the value of the sttlmDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSttlmDt(XMLGregorianCalendar value) {
        this.sttlmDt = value;
    }

}
