//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.05 at 09:22:09 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.998.231", 
xmlns = {
@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:iso:std:iso:20022:tech:xsd:camt.998.231", prefix = "bimo")},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.belejanor.switcher.bimo.pacs.camt_998_231;

