
package com.belejanor.switcher.implementations.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Fri Mar 16 16:27:46 COT 2018
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "debit", namespace = "http://implementations.middleware.fitbank.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "debit", namespace = "http://implementations.middleware.fitbank.com")

public class Debit {

    @XmlElement(name = "DTORequestDebit" , namespace = "http://implementations.middleware.fitbank.com")
    private com.belejanor.switcher.electroniccash.DTORequestDebit arg0;

    public com.belejanor.switcher.electroniccash.DTORequestDebit getArg0() {
        return this.arg0;
    }

    public void setArg0(com.belejanor.switcher.electroniccash.DTORequestDebit newArg0)  {
        this.arg0 = newArg0;
    }

}

