
package com.belejanor.switcher.implementations.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Tue May 29 12:37:27 COT 2018
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "movementsAccountResponse", namespace = "http://implementations.middleware.fitbank.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "movementsAccountResponse", namespace = "http://implementations.middleware.fitbank.com/")

public class MovementsAccountResponse {

    @XmlElement(name = "movementsAccountResponse")
    private com.belejanor.switcher.credencial.MovementsCredencialResponse _return;

    public com.belejanor.switcher.credencial.MovementsCredencialResponse getReturn() {
        return this._return;
    }

    public void setReturn(com.belejanor.switcher.credencial.MovementsCredencialResponse new_return)  {
        this._return = new_return;
    }

}

