
package com.belejanor.switcher.implementations.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Mon Feb 06 16:38:19 COT 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "processtransactionResponse", namespace = "http://implementations.middleware.fitbank.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processtransactionResponse", namespace = "http://implementations.middleware.fitbank.com/")

public class ProcesstransactionResponse {

    @XmlElement(name = "processtransactionReturn")
    private com.belejanor.switcher.cscoreswitch.Iso8583 _return;

    public com.belejanor.switcher.cscoreswitch.Iso8583 getReturn() {
        return this._return;
    }

    public void setReturn(com.belejanor.switcher.cscoreswitch.Iso8583 new_return)  {
        this._return = new_return;
    }

}

