
package com.belejanor.switcher.implementations.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
//import org.apache.cxf.interceptor.InInterceptors;

/**
 * This class was generated by Apache CXF 3.1.10
 * Mon Feb 06 16:38:19 COT 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "processtransaction", namespace = "http://implementations.middleware.fitbank.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processtransaction", namespace = "http://implementations.middleware.fitbank.com/")
//@InInterceptors(interceptors = "com.fitbank.middleware.cscoreswitch.BasicAuthAuthorizationInterceptor")
public class Processtransaction {

    @XmlElement(name = "Iso8583")
    private com.belejanor.switcher.cscoreswitch.Iso8583 arg0;

    public com.belejanor.switcher.cscoreswitch.Iso8583 getArg0() {
        return this.arg0;
    }

    public void setArg0(com.belejanor.switcher.cscoreswitch.Iso8583 newArg0)  {
        this.arg0 = newArg0;
    }

}

