//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.11 at 12:21:52 PM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_462;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidateOTP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidateOTP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrgnlGrpInf" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}OriginalGroupInformation"/>
 *         &lt;element name="AccountId" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}AccountId"/>
 *         &lt;element name="PartyId" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}Max35Text" minOccurs="0"/>
 *         &lt;element name="PartyPhone" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}PhoneType" minOccurs="0"/>
 *         &lt;element name="TxSts" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}StatusCode"/>
 *         &lt;element name="StsRsnInf" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.462}StatusReasonInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidateOTP", propOrder = {
    "orgnlGrpInf",
    "accountId",
    "partyId",
    "partyPhone",
    "txSts",
    "stsRsnInf"
})
public class ValidateOTP implements Serializable{

    @XmlElement(name = "OrgnlGrpInf", required = true)
    protected OriginalGroupInformation orgnlGrpInf;
    @XmlElement(name = "AccountId", required = true)
    protected String accountId;
    @XmlElement(name = "PartyId")
    protected String partyId;
    @XmlElement(name = "PartyPhone")
    protected String partyPhone;
    @XmlElement(name = "TxSts", required = true)
    protected StatusCode txSts;
    @XmlElement(name = "StsRsnInf", required = true)
    protected StatusReasonInformation stsRsnInf;

    /**
     * Gets the value of the orgnlGrpInf property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalGroupInformation }
     *     
     */
    public OriginalGroupInformation getOrgnlGrpInf() {
        return orgnlGrpInf;
    }

    /**
     * Sets the value of the orgnlGrpInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalGroupInformation }
     *     
     */
    public void setOrgnlGrpInf(OriginalGroupInformation value) {
        this.orgnlGrpInf = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountId(String value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the partyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * Sets the value of the partyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyId(String value) {
        this.partyId = value;
    }

    /**
     * Gets the value of the partyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPhone() {
        return partyPhone;
    }

    /**
     * Sets the value of the partyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPhone(String value) {
        this.partyPhone = value;
    }

    /**
     * Gets the value of the txSts property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCode }
     *     
     */
    public StatusCode getTxSts() {
        return txSts;
    }

    /**
     * Sets the value of the txSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCode }
     *     
     */
    public void setTxSts(StatusCode value) {
        this.txSts = value;
    }

    /**
     * Gets the value of the stsRsnInf property.
     * 
     * @return
     *     possible object is
     *     {@link StatusReasonInformation }
     *     
     */
    public StatusReasonInformation getStsRsnInf() {
        return stsRsnInf;
    }

    /**
     * Sets the value of the stsRsnInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusReasonInformation }
     *     
     */
    public void setStsRsnInf(StatusReasonInformation value) {
        this.stsRsnInf = value;
    }

}
