//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 08:58:22 AM COT 
//


package com.belejanor.switcher.bimo.pacs.camt_998_221;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AcctUnEnroll complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctUnEnroll">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartyPrdType" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.221}Max35Text"/>
 *         &lt;element name="PartyPhone" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.221}PhoneType"/>
 *         &lt;element name="AccInfo" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.221}AccountId"/>
 *         &lt;element name="Rsn" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.221}Max35Text" minOccurs="0"/>
 *         &lt;element name="SttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:camt.998.221}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctUnEnroll", propOrder = {
    "partyPrdType",
    "partyPhone",
    "accInfo",
    "rsn",
    "sttlmDt"
})
public class AcctUnEnroll implements Serializable{

    @XmlElement(name = "PartyPrdType", required = true)
    protected String partyPrdType;
    @XmlElement(name = "PartyPhone", required = true)
    protected String partyPhone;
    @XmlElement(name = "AccInfo", required = true)
    protected String accInfo;
    @XmlElement(name = "Rsn")
    protected String rsn;
    @XmlElement(name = "SttlmDt", required = true)
    protected XMLGregorianCalendar sttlmDt;

    /**
     * Gets the value of the partyPrdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPrdType() {
        return partyPrdType;
    }

    /**
     * Sets the value of the partyPrdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPrdType(String value) {
        this.partyPrdType = value;
    }

    /**
     * Gets the value of the partyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyPhone() {
        return partyPhone;
    }

    /**
     * Sets the value of the partyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyPhone(String value) {
        this.partyPhone = value;
    }

    /**
     * Gets the value of the accInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccInfo() {
        return accInfo;
    }

    /**
     * Sets the value of the accInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccInfo(String value) {
        this.accInfo = value;
    }

    /**
     * Gets the value of the rsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsn() {
        return rsn;
    }

    /**
     * Sets the value of the rsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsn(String value) {
        this.rsn = value;
    }

    /**
     * Gets the value of the sttlmDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSttlmDt() {
        return sttlmDt;
    }

    /**
     * Sets the value of the sttlmDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSttlmDt(XMLGregorianCalendar value) {
        this.sttlmDt = value;
    }

}
