//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.15 at 01:12:40 PM COT 
//


package com.belejanor.switcher.bimo.pacs.pacs_002_022;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentsV03 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentsV03">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConfCode" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.08.022}Max35Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentsV03", propOrder = {
    "confCode"
})
public class ContentsV03 implements Serializable{

    @XmlElement(name = "ConfCode", required = true)
    protected String confCode;

    /**
     * Gets the value of the confCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfCode() {
        return confCode;
    }

    /**
     * Sets the value of the confCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfCode(String value) {
        this.confCode = value;
    }

}
